apiVersion: v1
kind: Service
metadata:
  name: redis-commander
spec:
  selector:
    app: redis-commander
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30000
  type: NodePort
